version: '3'

services:

  bot:
    image: "link_bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/app"
    volumes:
      - .:/app
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    depends_on:
      - redis_database
      - pg_database

  redis_database:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --port $REDIS_PORT --save 20 1 --loglevel warning
    env_file:
      - ".env"
    volumes:
      - /home/kailex/redis/data:/redis/data

  pg_database:
    image: postgres:13-alpine
    ports:
      - "5439:5432"
    restart: always
    volumes:
      - /home/kailex/pgdata:/var/lib/postgresql/data
    command: "postgres -c max_connections=150
            -c shared_buffers=512MB -c effective_cache_size=1536MB
            -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB
            -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200
            -c work_mem=3495kB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=2
            -c max_parallel_workers_per_gather=1 -c max_parallel_workers=2 -c max_parallel_maintenance_workers=1"
    env_file:
      - '.env'
