"""Updated at field added

Revision ID: fee2eef8286d
Revises: 8b9d3d42a4d4
Create Date: 2024-03-14 17:57:08.210236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fee2eef8286d'
down_revision: Union[str, None] = '8b9d3d42a4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('updated_at', postgresql.TIMESTAMP(), default=None))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('chats', 'updated_at')
    # ### end Alembic commands ###
